# Generated by Django 3.2.13 on 2023-09-20 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desvantagens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('argumento', models.CharField(max_length=70)),
                ('desvpessoais', models.CharField(max_length=70)),
                ('desvtrabalho', models.CharField(choices=[('I', 'Impossivel'), ('A', 'Atrapalha'), ('NL', 'Naoligo')], max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Tabela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('coluna2', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vantagens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('argumento', models.CharField(max_length=70)),
                ('vanttrabalho', models.CharField(choices=[('MU', 'Muitoutil'), ('L', 'Legal'), ('TF', 'Tantofaz')], max_length=70)),
                ('vantlazer', models.CharField(max_length=70)),
            ],
        ),
    ]
